[package]
name = "glazeui"
version = "0.0.1"
edition = "2024"
license = "Apache-2.0"

[workspace]
members = [
  "crates/glazeui_core",
  "crates/glazeui_components"
, "crates/glazeui_layout", "crates/glazeui_renderer"]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2024"
license = "Apache-2.0"

[workspace.dependencies]
glazeui_core = { path = "crates/glazeui_core" }
glazeui_components = { path = "crates/glazeui_components" }
glazeui_layout = { path = "crates/glazeui_layout" }
glazeui_renderer = { path = "crates/glazeui_renderer" }
winit = "0.30.12"
wgpu = "28.0.0"
pollster = "0.4.0"
taffy = "0.9.2"

[dependencies]
glazeui_core = { path = "crates/glazeui_core" }
glazeui_components = { path = "crates/glazeui_components" }
glazeui_layout = { path = "crates/glazeui_layout" }
glazeui_renderer = { path = "crates/glazeui_renderer" }
winit = "0.30.12"
wgpu = "28.0.0"
pollster = "0.4.0"
taffy = "0.9.2"
