[package]
name = "glazeui"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
description = { workspace = true }

[dependencies]
winit = "0.30.12"
wgpu = "28.0.0"
pollster = "0.4.0"
taffy = "0.9.2"
glyphon = "0.10.0"
bytemuck = "1.24.0"
image = "0.25.9"

[workspace]
members = [
    "examples/*"
]

[workspace.package]
version = "0.1.1"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/dest-hq/glazeui"
categories = ["gui"]
keywords = ["gui", "ui", "interface", "widgets"]
description = "Cross-platform GUI library, written in Rust"

[workspace.dependencies]
glazeui = { version = "0.1.1", path = "." }
