[package]
name = "glaze-ui"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[workspace]
members = [
  "crates/glaze_core",
  "crates/glaze_components"
, "crates/glaze_layout"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[workspace.dependencies]
glaze_core = { path = "crates/glaze_core" }
glaze_components = { path = "crates/glaze_components" }
glaze_layout = { path = "crates/glaze_layout" }

[dependencies]
glaze_core = { path = "crates/glaze_core" }
glaze_components = { path = "crates/glaze_components" }
glaze_layout = { path = "crates/glaze_layout" }
