[package]
name = "glazeui_components"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
glazeui_core = { workspace = true }
taffy = { workspace = true }
cosmic-text = "0.15.0"
