[package]
name = "glaze_components"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
glaze_core = { workspace = true }
taffy = "0.9.2"
cosmic-text = "0.15.0"
