name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  run-linux:
    name: Run Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run counter
        run: cargo build -p counter --verbose
      # - name: Run tests
      #   run: cargo test -p counter --verbose

  run-macos:
    name: Run MacOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run counter
        run: cargo build -p counter --verbose
      # - name: Run tests
      #   run: cargo test -p counter --verbose

  run-windows:
    name: Run Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run counter
        run: cargo build -p counter --verbose
      # - name: Run tests
      #   run: cargo test -p counter --verbose
  build_raspberry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install cross
        run: cargo install cross

      - name: Build counter for Raspberry Pi 3/4 (64-bit)
        run: cross build --verbose --profile release --package counter --target aarch64-unknown-linux-gnu

      - name: Build counter for Raspberry Pi 2/3/4 (32-bit)
        run: cross build --verbose --profile release --package counter --target armv7-unknown-linux-gnueabihf
